const path = {
  home: '/',
  login: '/login',
  register: '/register',
  logout: '/logout',
  supportCenter: '/support',
  term: '/term',
  upload: '/upload',
  user: '/user',
  userDetail: '/user/detail',
  userSetting: '/user/setting',
  userStores: '/user/my-stores',
  userCart: '/user/my-cart',
  userCheckout: '/user/checkout',
  userOrders: '/user/my-orders',
  userOrderDetail: '/user/my-orders/:orderId',
  // shop
  createShop: '/create-shop',
  shopOnline: '/shop-online',
  shopOnlineDetail: '/shop-online/:shopId',
  shopOnlineProductDetail: '/shop-online/products/:productId',
  shopOnlineCart: '/shop-online/cart',
  shopOnlineCheckout: '/shop-online/checkout',
  shop: '/shop',
  shopSetting: '/shop/:shopId/setting',
  shopManageProducts: '/shop/:shopId/my-products',
  shopManageOrder: '/shop/:shopId/orders',
  shopOrderDetail: '/shop/:shopId/orders/:orderId',
  shopEditOrder: '/shop/edit-order/:orderId',
  shopProductDetail: '/shop/my-products/:productId',
  // product
  category: '/category',
  categoryFeatured: '/category-featured/:featureId',
  categoryProduct: '/category/:categoryId',
  products: '/products',
  productSearchResult: '/products/search-results',
  productDetail: '/products/:productId',
  customProduct: '/editor/:productId',
  editProduct: '/products/details/:productId',
  // Chat
  shopChats: '/shop/:shopId/chats',
  userChats: '/user/:userId/chats',
  chatDetail: '/chats/:chatId'
} as const

export default path
